[package]
name = "SpectralEngine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dsp = "0.10.2"
assert_approx_eq = "1.1.0"

